# -*- coding: utf-8 -*-
"""JSON_Refiner_Advanced_Edition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zvi9ubV8dhWFGdUoov5I3I0wr3xf-Kwz
"""

!pip install gradio jsonschema

import gradio as gr
import json
import re
from jsonschema import validate

# -------- CORE LOGIC --------

history_store = []

def infer_type(v):
    v = str(v).strip()
    if v.lower() in ["true","yes","on"]: return True
    if v.lower() in ["false","no","off"]: return False
    if v.lower() in ["null","none","nil"]: return None
    try:
        if "." in v: return float(v)
        return int(v)
    except:
        return v


def convert_case(key, style):

    if style=="snake_case":
        temp=re.sub(r'[\s\-]+','_',key)
        snake=re.sub(r'(?<!^)(?=[A-Z])','_',temp).lower()
        return re.sub(r'_{2,}','_',snake)

    elif style=="camelCase":
        parts=re.split(r'[_\-\s]+',key)
        return parts[0].lower()+''.join(p.capitalize() for p in parts[1:])

    elif style=="PascalCase":
        return ''.join(p.capitalize() for p in re.split(r'[_\-\s]+',key))

    elif style=="kebab-case":
        temp=re.sub(r'[\s_]+','-',key)
        kebab=re.sub(r'(?<!^)(?=[A-Z])','-',temp).lower()
        return re.sub(r'-{2,}','-',kebab)

    return key


# -------- CORE REFINING --------

def core_refine(text,style,remove_nulls):

    if not text.strip():
        return "", "⚠️ Enter data"

    try:
        try:
            result=json.loads(text)
            status="✅ JSON detected"
        except:
            result={}
            lines=[l for l in text.split("\n") if ":" in l]

            for line in lines:
                k,v=line.split(":",1)
                key=convert_case(k.strip(),style)
                result[key]=infer_type(v.strip())

            status="✅ Converted list"

        if remove_nulls:
            result={k:v for k,v in result.items() if v is not None}

        out=json.dumps(result,indent=4)

        history_store.append(out)

        return out,status

    except Exception as e:
        return "",f"❌ Error {str(e)}"


# -------- VALIDATION --------

def validate_json(json_str,schema_str):

    try:
        data=json.loads(json_str)

        if schema_str.strip()=="":
            return json_str,"✅ JSON Valid"

        validate(instance=data,schema=json.loads(schema_str))

        return json_str,"✅ Schema Valid"

    except Exception as e:
        return json_str,f"❌ Validation Error {str(e)}"


# -------- CASE CONVERSION --------

def case_convert(json_str,style):

    try:
        data=json.loads(json_str)

        new={}
        for k,v in data.items():
            new[convert_case(k,style)]=v

        out=json.dumps(new,indent=4)

        history_store.append(out)

        return out,"🔤 Case Converted"

    except:
        return json_str,"⚠️ Invalid JSON"


# -------- MERGE JSON --------

def merge_json(json1,json2):

    try:
        d1=json.loads(json1)
        d2=json.loads(json2)

        merged={**d1,**d2}

        out=json.dumps(merged,indent=4)

        history_store.append(out)

        return out,"🔗 JSON Merged"

    except:
        return json1,"⚠️ Invalid JSON"


# -------- FLATTEN --------

def flatten_json(json_str):

    try:
        data=json.loads(json_str)
        flat={}

        def walk(x,name=""):
            if isinstance(x,dict):
                for a in x:
                    walk(x[a],f"{name}{a}.")
            else:
                flat[name[:-1]]=x

        walk(data)

        out=json.dumps(flat,indent=4)

        history_store.append(out)

        return out,"📉 Flattened"

    except:
        return json_str,"⚠️ Invalid JSON"


# -------- UNFLATTEN --------

def unflatten_json(json_str):

    try:
        data=json.loads(json_str)

        res={}

        for k,v in data.items():
            parts=k.split(".")
            d=res

            for p in parts[:-1]:
                d=d.setdefault(p,{})

            d[parts[-1]]=v

        out=json.dumps(res,indent=4)

        history_store.append(out)

        return out,"📈 Unflattened"

    except:
        return json_str,"⚠️ Invalid JSON"


# -------- HISTORY --------

def show_history():

    if not history_store:
        return "No history","🕒 Empty"

    return "\n\n".join(history_store),"🕒 History loaded"


# -------- GUIDE --------

def show_guide():

    text="""
Guide:

Core Refining → Convert Key:Value to JSON
Validation → Validate JSON with schema
Case Conversion → Change naming style
Merge JSON → Merge two JSON objects
Flatten → Convert nested JSON
Unflatten → Restore structure
History → Show previous results
"""

    return text,"📘 Guide"


# -------- CLEAR --------

def clear_all():
    return "", "", "Status: Ready"


# -------- UI --------

with gr.Blocks(title="JSON Refiner Pro") as demo:

    gr.Markdown("# JSON Refiner Advanced")

    with gr.Row():

        with gr.Column():

            inp=gr.Textbox(label="Input JSON / List",lines=10)

            inp2=gr.Textbox(label="Merge JSON (optional)",lines=5)

            schema=gr.Textbox(label="Schema",lines=3)

            style=gr.Dropdown(["snake_case","camelCase","PascalCase","kebab-case"],value="snake_case")

            rem=gr.Checkbox(label="Remove Nulls",value=True)

        with gr.Column():

            status=gr.Markdown("Status: Ready")

            # FIXED OUTPUT BOX
            out=gr.Textbox(label="Output",lines=18,interactive=False,show_copy_button=True)

    with gr.Row():

        btn_core=gr.Button("Core Refining")

        btn_val=gr.Button("Validation")

        btn_case=gr.Button("Case Conversion")

        btn_merge=gr.Button("Merge JSON")

        btn_flat=gr.Button("Flatten")

        btn_unflat=gr.Button("Unflatten")

        btn_hist=gr.Button("History")

        btn_guide=gr.Button("Guide")

        btn_clear=gr.Button("Clear")

    btn_core.click(core_refine,[inp,style,rem],[out,status])

    btn_val.click(validate_json,[out,schema],[out,status])

    btn_case.click(case_convert,[out,style],[out,status])

    btn_merge.click(merge_json,[out,inp2],[out,status])

    btn_flat.click(flatten_json,out,[out,status])

    btn_unflat.click(unflatten_json,out,[out,status])

    btn_hist.click(show_history,[],[out,status])

    btn_guide.click(show_guide,[],[out,status])

    btn_clear.click(clear_all,[],[inp,out,status])


demo.launch()